<a href="https://colab.research.google.com/github/Chelladuraimct/ColabFiles/blob/main/Data_Query_Mental_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
**Data Merging and Lookup Operations with Pandas**

---

In [ ]:
#Import Libraries
import pandas as pd
import numpy as np

---
**TASK 1: Data Preparation and Missing Value Handling**

---

**Create DataFrames**

In [ ]:
# Students Data
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

# Enrollments Data
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}

# Scores Data
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

# Convert to DataFrames
students_df = pd.DataFrame(students_data)
enrollments_df = pd.DataFrame(enrollments_data)
scores_df = pd.DataFrame(scores_data)

print("Original Students DataFrame:")
display(students_df)

Original Students DataFrame:

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi

---
**Null Value Analysis**

---

In [ ]:
print("Null Value Analysis:")

for column in students_df.columns:
    null_count = students_df[column].isnull().sum()
    percentage = (null_count / len(students_df)) * 100
    print(f"Column: {column}, Nulls: {null_count} ({percentage:.2f}%)")

Null Value Analysis:
Column: student_id, Nulls: 0 (0.00%)
Column: name, Nulls: 1 (14.29%)
Column: email, Nulls: 1 (14.29%)
Column: city, Nulls: 1 (14.29%)

---
**Data Cleaning**

---
**Fill Missing City Values**

In [ ]:
students_df['city'].fillna('Unknown', inplace=True)

/tmp/ipykernel_299/2338393633.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students_df['city'].fillna('Unknown', inplace=True)

**Drop Rows Where Name is Missing**

In [ ]:
students_df = students_df.dropna(subset=['name'])

**Display Cleaned DataFrame**

In [ ]:
print("Cleaned Students DataFrame:")
display(students_df)
print("Total Rows:", len(students_df))

Cleaned Students DataFrame:

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

Total Rows: 6

---
**TASK 2: Multiple Join Operations**

---
**Inner Join**

In [ ]:
inner_join = pd.merge(students_df, enrollments_df, on='student_id', how='inner')

print("Inner Join Result:")
display(inner_join)

print("Total Students in Result:", len(inner_join))

Inner Join Result:

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10

Total Students in Result: 3

Explanation

Students excluded: 104, 106, 107

Reason:
They do not exist in the enrollments table, so inner join removes them.

**Left Join**

In [ ]:
left_join = pd.merge(students_df, enrollments_df, on='student_id', how='left')

print("Left Join Result:")
display(left_join)

print("Total Rows:", len(left_join))

#Students With No Course
no_course = left_join[left_join['course_name'].isnull()]
print("\nStudents with NULL course_name:")
display(no_course[['student_id','name']])

Left Join Result:

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN

Total Rows: 6

Students with NULL course_name:

   student_id   name
2         104  David
4         106  Frank
5         107  Grace

Explanation:
Students 104, 106, 107 have no enrollments.

**Right Join**

In [ ]:
right_join = pd.merge(students_df, enrollments_df, on='student_id', how='right')

print("Right Join Result:")
display(right_join)

print("Total Rows:", len(right_join))

#Students Without Names
missing_names = right_join[right_join['name'].isnull()]
print("\nStudent IDs without names:")
display(missing_names[['student_id','course_name']])

Right Join Result:

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,108,NaN,NaN,NaN,AI,2024-02-15
5,109,NaN,NaN,NaN,Python,2024-03-01

Total Rows: 6

Student IDs without names:

   student_id course_name
2         103      Python
4         108          AI
5         109      Python

Explanation:
Student IDs 108 and 109 exist in enrollments but not in students table.

**Full Outer Join**

In [ ]:
outer_join = pd.merge(students_df, enrollments_df, on='student_id', how='outer')

print("Outer Join Result:")
display(outer_join)

print("Total Rows:", len(outer_join))

#Rows With Missing Values
missing_rows = outer_join[
    (outer_join['name'].isnull()) |
    (outer_join['course_name'].isnull())
]

print("\nRows with Missing Name OR Course:")
display(missing_rows)

#Merge Indicator Analysis
outer_indicator = pd.merge(
    students_df,
    enrollments_df,
    on='student_id',
    how='outer',
    indicator=True
)

display(outer_indicator)

print("\nMerge Source Distribution:")
print(outer_indicator['_merge'].value_counts())

Outer Join Result:

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,104,David,None,Mumbai,NaN,NaN
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
5,106,Frank,frank@email.com,Chennai,NaN,NaN
6,107,Grace,grace@email.com,Delhi,NaN,NaN
7,108,NaN,NaN,NaN,AI,2024-02-15
8,109,NaN,NaN,NaN,Python,2024-03-01

Total Rows: 9

Rows with Missing Name OR Course:

   student_id   name            email     city course_name enrollment_date
2         103    NaN              NaN      NaN      Python      2024-02-01
3         104  David             None   Mumbai         NaN             NaN
5         106  Frank  frank@email.com  Chennai         NaN             NaN
6         107  Grace  grace@email.com    Delhi         NaN             NaN
7         108    NaN              NaN      NaN          AI      2024-02-15
8         109    NaN              NaN      NaN      Python      2024-03-01

,student_id,name,email,city,course_name,enrollment_date,_merge
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15,both
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20,both
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10,both
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only

Merge Source Distribution:
_merge
left_only     3
right_only    3
both          3
Name: count, dtype: int64

---
**TASK 3: Lookup Operation and Automation**

---
**Lookup Using Dictionary + map()**

In [ ]:
# Create dictionary
score_lookup = scores_df.set_index('student_id')['exam_score'].to_dict()

# Map scores
students_df['exam_score'] = students_df['student_id'].map(score_lookup)

print("Students with Exam Scores:")
display(students_df[['student_id','name','exam_score']])

Students with Exam Scores:

   student_id   name  exam_score
0         101  Alice        85.0
1         102    Bob        92.0
3         104  David        78.0
4         105   Emma        88.0
5         106  Frank        95.0
6         107  Grace         NaN

Students without exam scores will show NaN.

**Same Operation Using Merge**

In [ ]:
merge_scores = pd.merge(
    students_df,
    scores_df,
    on='student_id',
    how='left'
)

display(merge_scores[['student_id','name','exam_score_y']])

   student_id   name  exam_score_y
0         101  Alice          85.0
1         102    Bob          92.0
2         104  David          78.0
3         105   Emma          88.0
4         106  Frank          95.0
5         107  Grace           NaN

**Simple Automation Function**

In [ ]:
def auto_merge(df1, df2, join_type, key_column):

    merged_df = pd.merge(
        df1,
        df2,
        on=key_column,
        how=join_type
    )

    result = {
        'result_df': merged_df,
        'row_count': len(merged_df),
        'join_type': join_type
    }

    return result

---
**Test Automation Function**

---
**Test 1: Inner Join**

In [ ]:
test1 = auto_merge(students_df, enrollments_df, 'inner', 'student_id')

print("Join Type:", test1['join_type'])
print("Rows in Result:", test1['row_count'])

display(test1['result_df'].head())

Join Type: inner
Rows in Result: 3

,student_id,name,email,city,exam_score,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,85.0,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,92.0,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,88.0,Machine Learning,2024-02-10

**Test 2: Left Join**

In [ ]:
test2 = auto_merge(students_df, enrollments_df, 'left', 'student_id')

print("Join Type:", test2['join_type'])
print("Rows in Result:", test2['row_count'])

display(test2['result_df'].head())

Join Type: left
Rows in Result: 6

,student_id,name,email,city,exam_score,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,85.0,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,92.0,Data Science,2024-01-20
2,104,David,None,Mumbai,78.0,NaN,NaN
3,105,Emma,emma@email.com,Unknown,88.0,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,95.0,NaN,NaN