<a href="https://colab.research.google.com/github/Chelladuraimct/ColabFiles/blob/main/Ecommerce_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
**Ecommerce Sales Analysis using Pandas**

---
**Import Libraries and Create Synthetic Dataset**

**Explanation**

Since the company database cannot be accessed, we create a synthetic dataset using Python’s random module and store it in a Pandas DataFrame.

**The dataset contains:**

| Column         | Description               |
| -------------- | ------------------------- |
| transaction_id | Unique transaction number |
| region         | Sales region              |
| category       | Product category          |
| salesperson    | Person who made the sale  |
| sales_amount   | Value of sale             |
| customer_id    | Customer identifier       |

In [ ]:
import pandas as pd
import random

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)

print(df.head(10))
print("\nDataset shape:", df.shape)

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

---
**Task 1: Basic Grouping and Single Aggregations**

---
**1.1 Total Sales by Region**

**Explanation**

We group the data by region and calculate the total sales amount using sum().

In [ ]:
region_sales = df.groupby('region')['sales_amount'].sum().reset_index()

# Sort descending
region_sales = region_sales.sort_values(by='sales_amount', ascending=False)

print(region_sales)

  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81

**1.2 Count Transactions by Category**

**Explanation**

We count the number of transactions per product category.

In [ ]:
category_transactions = df.groupby('category')['transaction_id'].count().reset_index()

print(category_transactions)

        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

**1.3 Average Sales per Salesperson**

**Explanation**

This calculates mean sales amount per salesperson.

In [ ]:
avg_salesperson = df.groupby('salesperson')['sales_amount'].mean().reset_index()

print(avg_salesperson)

  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

---
**Task 2: Multi-Column Grouping and Multiple Aggregations**

---

**2.1 Total Sales by Region AND Category**

**Explanation**

Grouping by multiple columns allows deeper insights such as regional performance of each category.

In [ ]:
region_category_sales = df.groupby(['region','category'])['sales_amount'].sum().reset_index()

print(region_category_sales.head())

  region       category  sales_amount
0   East          Books      20027.53
1   East       Clothing      19926.20
2   East    Electronics      22791.55
3   East  Home & Garden      15949.08
4   East         Sports      16495.45

**2.2 Multiple Metrics per Salesperson**

**Explanation**

**Using agg() we calculate:**

*   Total Sales
*   Average Sales
*   Transaction Count

In [ ]:
salesperson_stats = df.groupby('salesperson')['sales_amount'] \
                      .agg(['sum','mean','count']) \
                      .reset_index()

# Sort by total sales
salesperson_stats = salesperson_stats.sort_values(by='sum', ascending=False)

print(salesperson_stats)

  salesperson        sum         mean  count
3       David  123436.64  2743.036444     45
5       Frank   98565.43  2464.135750     40
4        Emma   82284.09  2493.457273     33
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
0       Alice   43965.51  1998.432273     22

**2.3 Category with Maximum Revenue**

**Explanation**

We calculate total sales per category and use idxmax() to find the category with the highest revenue.

In [ ]:
category_sales = df.groupby('category')['sales_amount'].sum()

top_category = category_sales.idxmax()

print("Category with maximum revenue:", top_category)

Category with maximum revenue: Electronics

---
**Task 3: Custom Aggregation and Complete Sales Report**

---
**3.1 and 3.2 Custom Aggregation Function**

**Explanation**

We create a custom function to calculate the range of sales values:

range = max - min

In [ ]:
def sales_range(x):
    return x.max() - x.min()

region_analysis = df.groupby('region')['sales_amount'] \
                    .agg(['sum','mean','min','max',sales_range]) \
                    .reset_index()

print(region_analysis)

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

**3.3 Final Summary Sales Report**

**Explanation**

We generate a region-wise sales report including:

*   Total sales
*   Average sales
*   Number of transactions

In [ ]:
final_report = df.groupby('region').agg({
    'sales_amount': ['sum','mean'],
    'customer_id': 'count'
}).reset_index()

print(final_report)

  region sales_amount              customer_id
                  sum         mean       count
0   East     95189.81  2213.716512          43
1  North    135181.16  2413.949286          56
2  South    158977.36  2789.076491          57
3   West    109383.07  2485.978864          44

**3.4 Explanation: Multi-Level Columns in Aggregation**

When using dictionary-based aggregation, Pandas produces multi-level column names.

**Example:**

sales_amount

    sum

    mean

customer_id

    count

This creates a hierarchical column structure:

| Level 1      | Level 2 |
| ------------ | ------- |
| sales_amount | sum     |
| sales_amount | mean    |
| customer_id  | count   |

**Difference from Single Aggregation**

**Single aggregation:**

In [ ]:
df.groupby('region')['sales_amount'].sum()

region
East      95189.81
North    135181.16
South    158977.36
West     109383.07
Name: sales_amount, dtype: float64

**Multi aggregation:**

In [ ]:
df.groupby('region').agg({
'sales_amount':['sum','mean']
})

       sales_amount
                sum         mean
region
East       95189.81  2213.716512
North     135181.16  2413.949286
South     158977.36  2789.076491
West      109383.07  2485.978864